dist: bionic
language: rust

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc
            - binutils-dev
            - libiberty-dev

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly
    include:
        - rust: stable
        - rust: beta
        - rust: nightly
jobs:
    include:
        - name: format
          script:
              - rustup component add rustfmt
              - cargo fmt --all -- --check
        - name: clippy
          script:
              - rustup component add clippy
              - cargo clippy
